# Generated by Django 4.1 on 2022-09-22 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Aplicacion', '0002_rename_usuario_usuario_username_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='avatares'),
        ),
    ]
